### ISSUE TITLE
This function to format input, enables the enigma class to get the input in the correct format

### ISSUE THREAD

**Issue by Dee68** [Dee68/CSD#2]
### **Acceptance criteria**
- [x] strictly adhere to the comment in the function definition
- [x] implement the function in java
- [ ] write a test for the function

### **Definition done**
When  a call is made in the main function as thus : Enigma.formatInputMessage("Test message. Working."), it should return a string like this:"TEST?MESSAGE€?WORKING€"
