### ISSUE TITLE
This formattedOutput function, enables the enigma class to get the required format when decoding

### ISSUE THREAD

**Issue by Dee68** [Dee68/CSD#3]
### **Acceptance criteria**
- [x] strictly adhere to the comments of the function
- [x] implement the function to letter
- [ ] write a test for the function

### **Definition done**
When a call is made in the main class like thus: Enigma.formattedOutputMessage( "TEST?MESSAGE€?WORKING€"), 
it should return a string as: "Test message. Working.
