### ISSUE TITLE
This function applyRotor, enables the enigma class  to add more encryption to the input string

### ISSUE THREAD

**Issue by Dee68** [Dee68/CSD#5]
### **Acceptance criteria**
- [x] strictly adhere to the definition
- [x] implement the function
- [ ] write a test for the function

### **Definition done**
When this function is called as thus: Enigma.applyRotor("apple","HFPMRIBTJWYDXQLGUKOVSNAZEC"),
it should return a string as thus: "HGGDRO"
