### ISSUE TITLE
This reverseRotor function, enables the enigma class to revert the encryption imposed by the apply rotor

### ISSUE THREAD

**Issue by Dee68** [Dee68/CSD#6]
### **Acceptance criteria**
- [x] strictly adhere to the comment on the function
- [x] implement the function to letter
- [ ] write a test for the function

### **Definition done**
When the function is called as thus: Enigma.reverseRotor("HGGDRO", "HFPMRIBTJWYDXQLGUKOVSNAZEC"),
should return a string as : "Apples"
