### ISSUE TITLE
This  encode function, enables the enigma class to encrypt the input string

### ISSUE THREAD

**Issue by Dee68** [Dee68/CSD#7]
### **Acceptance criteria**
- [x] strictly adhere to the comments
- [x] implement the function to letter
- [ ] write a test for the function

### **Definition done**
When the function encode is called  as thus Enigma.encode("Hello world", 4, rotors): 
if :  List<String> rotors = new ArrayList<String>();
        rotors.add("BDFHJLCPRTXVZNYEIWGAKMUSQO");
        rotors.add("AJDKSIRUXBLHWTMCQGZNPYFVOE");
        rotors.add("EKMFLGDQVZNTOWYHXUSPAIBRCJ");
it should return a string as: CDSSU?ZUBSM
