### ISSUE TITLE
This decode function, enables the enigma class to return a correct decrypted string

### ISSUE THREAD

**Issue by Dee68** [Dee68/CSD#8]
### **Acceptance criteria**
- [ ] strictly adhere to the comments
- [ ] implement the function to letter
- [ ] write a test for the function

### **Definition done**
When the function is called as thus: Enigma.decode("CDSSU?ZUBSM", 4, rotors),
if:  List<String> rotors = new ArrayList<String>();
        rotors.add("BDFHJLCPRTXVZNYEIWGAKMUSQO");
        rotors.add("AJDKSIRUXBLHWTMCQGZNPYFVOE");
        rotors.add("EKMFLGDQVZNTOWYHXUSPAIBRCJ");
it should return a string : "Hello world"

**Comment by Dee68** [comment]
Not everything seems fine.

**Comment by Dee68** [comment]
Oh!, everything is ok.
